# Generated by Django 4.1 on 2022-08-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIG', 'High'), ('PRE', 'Premium')], max_length=3, null=True),
        ),
    ]
