# Generated by Django 4.1 on 2022-08-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='subscription',
            field=models.CharField(blank=True, choices=[('PL', 'Plus sub'), ('NP', 'Not plus sub')], default='PL', max_length=2, null=True),
        ),
    ]
