# Generated by Django 4.1 on 2022-08-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='subscription',
            field=models.CharField(blank=True, choices=[('PL', 'Plus member'), ('NP', 'Not plus member')], default='PL', max_length=2, null=True),
        ),
    ]
