# Generated by Django 4.1 on 2022-08-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='subscription',
            field=models.CharField(blank=True, choices=[('PL', 'Plus game'), ('NP', 'Not plus game')], default='NP', max_length=2, null=True),
        ),
    ]
