# Generated by Django 4.1 on 2022-08-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_game_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_history',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
