# Generated by Django 4.1 on 2022-08-09 20:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_is_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
