# Generated by Django 4.1 on 2022-08-09 20:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_game_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
